---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-google_chrome
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-fedora33}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
    tmpfs:
      - /run
      - /tmp
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
