---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Gather package facts
    package_facts:
  - name: Check google-chrome-stable package is installed
    assert:
      that: ansible_facts.packages['google-chrome-stable'] | length > 0
